### ISSUE TITLE
DROP ROLE "pg_signal_backend"

### ISSUE THREAD

**Issue by rumaxi** [larskanis/pg-ldap-sync#14]
PostgreSQL 9.6.4, Debian GNU/Linux 9.1, clean installation.

pg-ldap-sync is trying to drop system role pg_signal_backend.

```
I, [2017-09-22T11:54:58.039771 #10234]  INFO -- : SQL: DROP ROLE "pg_signal_backend"

/var/lib/gems/2.3.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:217:in `exec': ERROR:  cannot drop role pg_signal_backend because it is required by the database system (PG::DependentObjectsStillExist)
	from /var/lib/gems/2.3.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:217:in `pg_exec_modify'
	from /var/lib/gems/2.3.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:232:in `drop_pg_role'
	from /var/lib/gems/2.3.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:238:in `block in sync_roles_to_pg'
	from /var/lib/gems/2.3.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:236:in `each'
	from /var/lib/gems/2.3.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:236:in `sync_roles_to_pg'
	from /var/lib/gems/2.3.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:330:in `start!'
	from /var/lib/gems/2.3.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:353:in `run'
	from /var/lib/gems/2.3.0/gems/pg-ldap-sync-0.1.1/bin/pg_ldap_sync:6:in `<top (required)>'
	from /usr/local/bin/pg_ldap_sync:22:in `load'
	from /usr/local/bin/pg_ldap_sync:22:in `<main>'
```

Quick and dirty workaround at 
/var/lib/gems/2.3.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:231
```
def drop_pg_role(role)
    unless role.name == "pg_signal_backend"
        pg_exec_modify "DROP ROLE \"#{role.name}\""
    end
end
```

**Comment by larskanis** [comment]
This is solved in pg-ladp-sync-0.2.0.
