### ISSUE TITLE
PG-LDAP-Sync on Windows 2012R2 Server

### ISSUE THREAD

**Issue by tosage** [larskanis/pg-ldap-sync#22]
Hy,

I try your program but i stop of this problem and i don't know why :/

```sh
PS C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\pg-ldap-sync-0.2.0\config> pg_ldap_sync -c config.yaml -vv -t
Traceback (most recent call last):
        9: from C:/Ruby25-x64/bin/pg_ldap_sync:23:in `<main>'
        8: from C:/Ruby25-x64/bin/pg_ldap_sync:23:in `load'
        7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/pg-ldap-sync-0.2.0/exe/pg_ldap_sync:6:in `<top (required)>'
        6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/pg-ldap-sync-0.2.0/lib/pg_ldap_sync/application.rb:355:in `run'
        5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/pg-ldap-sync-0.2.0/lib/pg_ldap_sync/application.rb:301:in `start!'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/pg-ldap-sync-0.2.0/lib/pg_ldap_sync/application.rb:43:in `read_config_file'
        3: from C:/Ruby25-x64/lib/ruby/2.5.0/psych.rb:263:in `load'
        2: from C:/Ruby25-x64/lib/ruby/2.5.0/psych.rb:350:in `parse'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/psych.rb:402:in `parse_stream'
C:/Ruby25-x64/lib/ruby/2.5.0/psych.rb:402:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 7 column 1 (Psych::SyntaxError)
PS C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\pg-ldap-sync-0.2.0\config>
```

If you have any advice, i take it :)

Thanks in advance

**Comment by larskanis** [comment]
> did not find expected key while parsing a block mapping at line 7 column 1

Your config file seems to be invalid. Please not, that it's a YAML file, where spaces matter. Can you upload it?

**Comment by tosage** [comment]
You find my config file below
[config.yaml.txt](https://github.com/larskanis/pg-ldap-sync/files/2036254/config.yaml.txt)

**Comment by larskanis** [comment]
There's a space before `ldap_users:` in line 19. It makes it an invalid YAML file.

**Comment by tosage** [comment]
Hy,

Thanks for help, now your code browse like a charm my AD but i have a SSPI authentication error on my postgres, my fault, i go understand what are my bad configuration :)

Thanks for your quick help !!!
